const tableColumns = [
  {
    field: "campaigns",
    headerName: "Campaigns",
    flex: 1,
    headerClassName: "custom-header",
    cellClassName: "custom-cell",
  },
  {
    field: "clicks",
    headerName: "Clicks",
    type: "number",
    flex: 1,
    headerClassName: "custom-header",
    cellClassName: "custom-cell",
  },
  {
    field: "cost",
    headerName: "Cost",
    type: "number",
    flex: 1,
    headerClassName: "custom-header",
    cellClassName: "custom-cell",
  },
  {
    field: "conversions",
    headerName: "Conversions",
    type: "number",
    flex: 1,
    headerClassName: "custom-header",
    cellClassName: "custom-cell",
  },
  {
    field: "revenue",
    headerName: "Revenue",
    type: "number",
    flex: 1,
    headerClassName: "custom-header",
    cellClassName: "custom-cell",
  },
];

const tableRows = [
  {
    id: 1,
    campaigns: "Cosmetics",
    clicks: 712,
    cost: "USD 8399",
    conversions: 35,
    revenue: "USD 4353",
  },
  {
    id: 2,
    campaigns: "Serums",
    clicks: 234,
    cost: "USD 8399",
    conversions: 42,
    revenue: "USD 4353",
  },
  {
    id: 3,
    campaigns: "Facewash",
    clicks: 243,
    cost: "USD 8399",
    conversions: 45,
    revenue: "USD 4353",
  },
  {
    id: 4,
    campaigns: "Shampoos",
    clicks: 5633,
    cost: "USD 8399",
    conversions: 16,
    revenue: "USD 4353",
  },
  {
    id: 5,
    campaigns: "Conditioners",
    clicks: 3652,
    cost: "USD 8399",
    conversions: 43,
    revenue: "USD 4353",
  },
  {
    id: 6,
    campaigns: "Facewash 2",
    clicks: 234,
    cost: "USD 8399",
    conversions: 150,
    revenue: "USD 4353",
  },
  {
    id: 7,
    campaigns: "Total",
    clicks: 10453,
    cost: "USD 58454",
    conversions: 356,
    revenue: "USD 24353",
  },
];

const chartColumns = [
  {
    field: "group",
    headerName: "Group",
    flex: 1,
    headerClassName: "custom-header",
    cellClassName: "custom-cell",
  },
  {
    field: "clicks",
    headerName: "Clicks",
    type: "number",
    flex: 1,
    headerClassName: "custom-header",
    cellClassName: "custom-cell",
  },
  {
    field: "cost",
    headerName: "Cost",
    type: "number",
    flex: 1,
    headerClassName: "custom-header",
    cellClassName: "custom-cell",
  },
  {
    field: "conversions",
    headerName: "Conversions",
    type: "number",
    flex: 1,
    headerClassName: "custom-header",
    cellClassName: "custom-cell",
  },
  {
    field: "revenue",
    headerName: "Revenue",
    type: "number",
    flex: 1,
    headerClassName: "custom-header",
    cellClassName: "custom-cell",
  },
];

const chartRows = [
  {
    id: 1,
    group: "Male",
    clicks: 712,
    cost: "USD 8399",
    conversions: 35,
    revenue: "USD 4353",
  },
  {
    id: 2,
    group: "Female",
    clicks: 234,
    cost: "USD 8399",
    conversions: 42,
    revenue: "USD 4353",
  },
  {
    id: 3,
    group: "Unknown",
    clicks: 243,
    cost: "USD 8399",
    conversions: 45,
    revenue: "USD 4353",
  },
  {
    id: 4,
    group: "Total",
    clicks: 1232,
    cost: "USD 3426",
    conversions: 126,
    revenue: "USD 1854",
  },
];

export { tableColumns, tableRows, chartColumns, chartRows };
